### ISSUE TITLE
MSVC

### ISSUE THREAD

**Issue by filipwasil** [filipwasil/fillwave#22]
Try:

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-undef")

**Comment by filipwasil** [comment]
Microsoft Visual compiler seem to not like us.

**Comment by KeramKeram** [comment]
I will try to check this in next week, but It will take time.

**Comment by KeramKeram** [comment]
CMakeFiles/fillwave.dir/src/core/buffers/VertexBufferBasic.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
VertexBufferBasic.cpp:(.text+0x93b): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/core/rendering/FramebufferGeometry.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
FramebufferGeometry.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/core/texturing/NoiseTexture3DArray.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
NoiseTexture3DArray.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/core/texturing/Texture3D.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Texture3D.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/Cursor.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Cursor.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/EmiterPointCPU.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
EmiterPointCPU.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/EmiterPointGPU.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
EmiterPointGPU.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/EmiterPointStep.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
EmiterPointStep.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/Entity.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Entity.cpp:(.text+0x93b): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/Impostor.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Impostor.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/Mesh.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Mesh.cpp:(.text+0x2f8): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/MeshTerrain.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
MeshTerrain.cpp:(.text+0x93b): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/Model.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Model.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/Skybox.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Skybox.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/Terrain.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Terrain.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/VoxelChunk.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
VoxelChunk.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/base/IEmiterPoint.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
IEmiterPoint.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/base/IReloadable.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
IReloadable.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/animations/Animator.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Animator.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/animations/Bone.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Bone.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/animations/Hinge.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Hinge.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/builders/BuilderEmiter.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
BuilderEmiter.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/models/builders/BuilderModel.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
BuilderModel.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/space/LightDirectional.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
LightDirectional.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/space/LightSpot.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
LightSpot.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/callbacks/FPSCallback.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
FPSCallback.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/loaders/ProgramLoader.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
ProgramLoader.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/management/LightSystem.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
LightSystem.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/management/TextureSystem.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
TextureSystem.cpp:(.text+0x93b): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/common/Debugger.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Debugger.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/common/IFocusable.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
IFocusable.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/renderers/IRendererCSPBRP.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
IRendererCSPBRP.cpp:(.text+0x93b): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/renderers/RendererDR.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
RendererDR.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/hud/Button.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Button.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/hud/HUD.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
HUD.cpp:(.text+0x0): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/hud/ProgressBar.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
ProgressBar.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
CMakeFiles/fillwave.dir/src/hud/Text.cpp.o: In function `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)':
Text.cpp:(.text+0x18a): multiple definition of `flw::flf::fopen_s(_IO_FILE**, char const*, char const*)'
CMakeFiles/fillwave.dir/src/Fillwave.cpp.o:Fillwave.cpp:(.text+0x93b): first defined here
collect2: error: ld returned 1 exit status
CMakeFiles/fillwave.dir/build.make:3008: polecenia dla obiektu 'libfillwave.so' nie powiodły się
make[2]: *** [libfillwave.so] Błąd 1
CMakeFiles/Makefile2:68: polecenia dla obiektu 'CMakeFiles/fillwave.dir/all' nie powiodły się
make[1]: *** [CMakeFiles/fillwave.dir/all] Błąd 2
Makefile:149: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 2
-- Eclipse version is set to 4.4 (Luna). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.
Building development package
CMake Warning (dev) at cmake/platform/LinuxDev.cmake:11 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:
