### ISSUE TITLE
Unable to locate package GLFW-3 on Ubuntu 14.04

### ISSUE THREAD

**Issue by MisiuMis** [filipwasil/fillwave#58]
I'm trying to set up environment on Ubuntu 14.04.
However I have a problem with installation of required packages: 

> E: Unable to locate package libglfw3
> E: Unable to locate package libglfw3-dev

I was trying to find a solution in the internet and I found that:

> Ubuntu 14.04 has GLFW 2 packaged as libglfw2 and libglfw-dev. Mint doesn't seem to have those packages, but you can probably use the Ubuntu ones since Mint 17 is based on Ubuntu 14.04.
> GLFW 3 isn't in Ubuntu 14.04, but it looks like it'll be in 14.10 (as libglfw3 and libglfw3-dev).
> (http://stackoverflow.com/questions/25151085/unable-to-locate-package-glfw-on-linux-mint)

Is it a known issue? :)
Maybe there is some workaround or I can use glfw2 somehow?

**Comment by filipwasil** [comment]
1)

```
            echo "deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/fillwave_ext.list
            echo "deb-src http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/fillwave_ext.list
```

sudo apt-get update

sudo apt-get install libglfw3 libglfw3-dev

This is the way i do it for wercker CI system

2)

git clone https://github.com/glfw/glfw && mkdir build && cd build && cmake ../glfw && make -j4 && sudo make install

**Comment by filipwasil** [comment]
2nd one is much better :+1:

**Comment by filipwasil** [comment]
GLFW2 has an old API.

**Comment by filipwasil** [comment]
GLFW is needed to build linux examples.
In options.cmake you can turn them off.

Note that there is are examples in qt - They do not use glfw.
