### ISSUE TITLE
gradle vs cmake (Hardcoded build scripts)

### ISSUE THREAD

**Issue by Lazaruspl** [filipwasil/fillwave#8]
Please check this:
https://github.com/filipwasil/fillwave/blob/master/scripts/build_windows.bat#L4
and also other build scripts.
This should be fixed :) I suggest moving to gradle in that way you'll avoid such problems.

**Comment by filipwasil** [comment]
https://github.com/filipwasil/fillwave/commit/6dcfb55687873c5ea150b1ffb90552cca6884e84

Fixed.

All projects and subprojects are built with Cmake in mind.
Cmake gives me full multiplatform and it seems to me gradle offerts the same functionality.

I will leave this issue to monitor the case.

**Comment by filipwasil** [comment]
CMake wins !
